TianYu.Admin/TianYu.Admin.WebMvc/Controllers/MQBusinessController.cs
using Newtonsoft.Json;
using TianYu.Core.Common; 
using TianYu.Admin.Domain.ViewModel;
using TianYu.Admin.Infrastructure.Enum;
using TianYu.Admin.Service.IService; 
using System.Collections.Generic; 
using System.Web.Mvc;
using TianYu.Core.Common.FilterAttribute.Mvc;
using TianYu.Core.Common.FilterAttribute.Api;

namespace TianYu.Admin.WebMvc.Controllers
{
    [ValidateLogin]
    public class MQBusinessController : BaseController
    {
        #region 变量
        private IMQBusinessConfigService _mQBusinessConfigService;
        #endregion

        #region 构造
        /// <summary>
        /// 构造
        /// </summary>
        /// <param name="mQBusinessConfigService"></param>
        public MQBusinessController(IMQBusinessConfigService mQBusinessConfigService)
        {
            this._mQBusinessConfigService = mQBusinessConfigService;
        }

        #endregion

        #region 视图

        [MvcPowerFilter]
        public ActionResult Index()
        {
            GetListItemByEnum();
            return View();
        }
        [MvcPowerFilter]
        public ActionResult Adds()
        {
            var model = new MQBusinessResponse();
            GetListItemByEnum();
            string mqRequestUrl= ConfigHelper.GetAppsettingValue("MqRequestUrl");
            var mqRequestList=JsonConvert.DeserializeObject<List<MqRequestUrlResponse>>(mqRequestUrl);
            List<SelectListItem> selectList = new List<SelectListItem>() { new SelectListItem() { Text = "请选择", Value = "" } };
            mqRequestList.ForEach(a => {
                selectList.Add(new SelectListItem() { Text=a.InterfaceName,Value=a.Url});
            });
            ViewBag.MqRequestUrl = selectList;



            return View(model);
        }
        [MvcPowerFilter]
        public ActionResult Edits(MQBusinessInfoRequest request)
        {
            GetListItemByEnum();
            var model = _mQBusinessConfigService.FindInfoById(request.ID);
            if (model == null)
            {
                return GoErrorPage("任务信息不存在或已被删除");
            }
            else
            {
                ViewBag.ConsumerType = (int)model.MqMessageType;
            }
            string mqRequestUrl = ConfigHelper.GetAppsettingValue("MqRequestUrl");
            var mqRequestList = JsonConvert.DeserializeObject<List<MqRequestUrlResponse>>(mqRequestUrl);
            List<SelectListItem> selectList = new List<SelectListItem>() { new SelectListItem() { Text="请选择",Value="" } };
            mqRequestList.ForEach(a => {
                selectList.Add(new SelectListItem() { Text = a.InterfaceName, Value = a.Url });
            });
            ViewBag.MqRequestUrl = selectList;
            return View(model);
        }
        [MvcPowerFilter]
        public ActionResult Detail(MQBusinessInfoRequest request)
        {
            GetListItemByEnum();
            if (request?.ID <= 0)
            {
                return GoErrorPage("参数传递错误");
            }

            var viewModel = _mQBusinessConfigService.FindInfoById(request.ID);
            if (viewModel == null)
            {
                return GoErrorPage("任务信息不存在或已被删除");
            }
            return View(viewModel);
        }

        private void GetListItemByEnum()
        {
            ViewBag.MQFailMsgType = base.GetSelectListItemByEnum<MQFailMsgType>();
            ViewBag.MQConsumerType = base.GetSelectListItemByEnum<MQConsumerType>();
            ViewBag.StatusType = base.GetSelectListItemByEnum<CommonStatusType>();
        }
        #endregion

        #region 动作

        /// <summary>
        /// 任务列表
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FindList(MQBusinessRequest request)
        {
            var res = _mQBusinessConfigService.FindList(request);
            return Content(res.ToJsonString());
        }


        /// <summary>
        /// 新增或更新
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult AddOrUpsert(MQBusinessAddOrUpsertRequest model)
        {
            var res = _mQBusinessConfigService.AddOrUpsert(model);
            return Content(res.ToJsonString());
        }
        #endregion
    }
}

TianYu.Admin/TianYu.Admin.WebMvc/Views/MQBusiness/Adds.cshtml
@model TianYu.Admin.Domain.ViewModel.MQBusinessResponse
@{
    ViewBag.Module = "消息队列列表";
    ViewBag.Title = "添加任务";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script>


        layui.use(['jquery', 'form'], function () {
            var form = layui.form,
                $ = layui.jquery;
            //提交表单数据
            form.on('submit(Save)', function (data) {
                //禁用提交按钮
                toggleSubmitStatus(data.elem);
                var param = data.field;
                var index = layer.load(1, { time: 60 * 1000 });
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("AddOrUpsert")',
                    data: param,
                    dataType: 'json',
                    success: function (res) {
                        layer.close(index);
                        if (res.Status == 200) {
                            res = res.Data;
                            if (res.Status == 1) {
                                //刷新列表
                                $(".layui-btn[lay-filter='formSearch']", window.parent.document).click();
                                layer.msg('保存成功', function () {
                                    //启用提交按钮
                                    toggleSubmitStatus(data.elem, true);
                                    //关闭当前弹出层
                                    var index = parent.layer.getFrameIndex(window.name);
                                    parent.layer.close(index);
                                });
                            }
                            else {
                                //启用提交按钮
                                toggleSubmitStatus(data.elem, true);
                                layer.msg(res.ErrorMessage);
                            }
                        }
                        else {
                            //启用提交按钮
                            toggleSubmitStatus(data.elem, true);
                            layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                        }
                    }
                });
            });

            form.on('select(MqMessageType)', function (data) {
                console.log(data);
                if (data.value == '0') {
                    $("#div_TimeInterval").show();
                }
                else {
                    $("#div_TimeInterval").hide();
                }
            });
            form.on('select(ApiUrlPrefix)', function (data) {
                var suffixUrl = $("#ApiUrlSuffix").val();
                $("#strapi").html(data.value + suffixUrl);
                $("#ApiUrl").val(data.value + suffixUrl);
            }); 

            $("#ApiUrlSuffix").change(function () {
                var apiUrlPrefix = $("#ApiUrlPrefix option:selected").val();
                var suffixUrl = $("#ApiUrlSuffix").val();
                $("#strapi").html(apiUrlPrefix + suffixUrl);
                $("#ApiUrl").val(apiUrlPrefix + suffixUrl);
            })
        });
    </script>
}

<div class="weadmin-body">
    <form class="layui-form">
        <div class="layui-form-item">
            <label class="layui-form-label">
                <input type="hidden" name="Id" value="@Model.Id" />
                <span class="we-red">*</span>任务名称：
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.BusinessName, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入任务名称" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>接口地址:
            </label>
            <div class="layui-input-block">
                <div class="layui-inline" style="width:120px">
                    @Html.DropDownListFor(x => x.ApiUrlPrefix, ViewBag.MqRequestUrl as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "ApiUrlPrefix" }, { "lay-verify", "required" } })
                </div>
                <div class="layui-inline" style="width:240px">
                    @Html.TextBoxFor(x => x.ApiUrlSuffix, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入接口地址" } })
                </div>
                <span id="strapi" style="display:block; width:460px"></span>
                @Html.HiddenFor(x=>x.ApiUrl)
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                MQ路由:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.RoutingKey, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入路由地址" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>交换机:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.Exchange, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入交换机地址" } })
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>队列名称:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.QueueName, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入队列名称" } })
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>消费方式:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.MqMessageType, ViewBag.MQConsumerType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "MqMessageType" } })
            </div>
        </div>

        <div class="layui-form-item" id="div_TimeInterval" style="display:none">
            <label class="layui-form-label">
                <span class="we-red"></span>时间间隔:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.TimeInterval, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "Pull获取消息时间间隔" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>异常重试次数:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.ExceptionNumber, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "异常重试次数" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>失败消息存储:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.IsSaveFailMessage, ViewBag.MQFailMsgType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "IsSaveFailMessage" } })
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>任务状态:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.Status, ViewBag.StatusType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "Status" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
            </label>
            <div class="layui-input-block">
                <button class="layui-btn" lay-filter="Save" lay-submit="">保存</button>
            </div>
        </div>

    </form>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/MQBusiness/Detail.cshtml
@{
    ViewBag.Module = "消息队列列表";
    ViewBag.Title = "消息队列任务详情";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="weadmin-body">
    <div class="layui-card">
        <div class="layui-card-header">消息队列任务详情</div>
        <div class="layui-card-body">
            <table class="layui-table details-info-table">
                <colgroup>
                    <col width="130">
                    <col>
                </colgroup>
                <tbody>
                    <tr>
                        <th class="layui-bg-gray">任务名称</th>
                        <td>@Model.BusinessName</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">接口地址</th>
                        <td>@Model.ApiUrl</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">路由名称</th>
                        <td>@Model.RoutingKey</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">交换机名称</th>
                        <td>@Model.Exchange</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">队列名称</th>
                        <td>@Model.QueueName</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">是否持久化</th>
                        <td>@(Model.IsProperties == 1 ? "持久化" : "非持久化")</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">消费方式</th>
                        <td>@Model.MQConsumerMsgStr</td>
                    </tr>
                    @if (Model.MqMessageType == 0)
                    {
                        <tr>
                            <th class="layui-bg-gray">时间间隔</th>
                            <td>@Model.TimeInterval</td>
                        </tr>
                    }
                    <tr>
                        <th class="layui-bg-gray">异常重试次数</th>
                        <td>@Model.ExceptionNumber</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">失败消息存储</th>
                        <td>@Model.MQFailMsgStr</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">任务状态</th>
                        <td>@Model.StatusStr</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/MQBusiness/Edits.cshtml
@model TianYu.Admin.Domain.ViewModel.MQBusinessResponse
@{
    ViewBag.Module = "消息队列列表";
    ViewBag.Title = "编辑消息队列";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script>
        layui.use(['jquery', 'form'], function () {
            var form = layui.form,
                $ = layui.jquery;
            $('#MqMessageType').val() == '0' ? $("#div_TimeInterval").show() : $("#div_TimeInterval").hide();
            //提交表单数据
            form.on('submit(Save)', function (data) {
                //禁用提交按钮
                toggleSubmitStatus(data.elem);
                var param = data.field;
                var index = layer.load(1, { time: 60 * 1000 });
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("AddOrUpsert")',
                    data: param,
                    dataType: 'json',
                    success: function (res) {
                        layer.close(index);
                        if (res.Status == 200) {
                            res = res.Data;
                            if (res.Status == 1) {
                                //刷新列表
                                $(".layui-btn[lay-filter='formSearch']", window.parent.document).click();
                                layer.msg('保存成功', function () {
                                    //启用提交按钮
                                    toggleSubmitStatus(data.elem, true);
                                    //关闭当前弹出层
                                    var index = parent.layer.getFrameIndex(window.name);
                                    parent.layer.close(index);
                                });
                            }
                            else {
                                //启用提交按钮
                                toggleSubmitStatus(data.elem, true);
                                layer.msg(res.ErrorMessage);
                            }
                        }
                        else {
                            //启用提交按钮
                            toggleSubmitStatus(data.elem, true);
                            layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                        }
                    }
                });
            });
            form.on('select(MqMessageType)', function (data) {
                if (data.value == '0') {
                    $("#div_TimeInterval").show();
                }
                else {
                    $("#div_TimeInterval").hide();
                }
            });

            form.on('select(ApiUrlPrefix)', function (data) {
                var suffixUrl = $("#ApiUrlSuffix").val();
                $("#strapi").html(data.value + suffixUrl);
                $("#ApiUrl").val(data.value + suffixUrl);
            });

            $("#ApiUrlSuffix").change(function () {
                var apiUrlPrefix = $("#ApiUrlPrefix option:selected").val();
                var suffixUrl = $("#ApiUrlSuffix").val();
                $("#strapi").html(apiUrlPrefix + suffixUrl);
                $("#ApiUrl").val(apiUrlPrefix + suffixUrl);
            })
        });
    </script>
}

<div class="weadmin-body">
    <form class="layui-form">
        <div class="layui-form-item">
            <label class="layui-form-label">
                <input type="hidden" name="Id" value="@Model.Id" />
                <span class="we-red">*</span>任务名称：
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.BusinessName, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入任务名称" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>接口地址:
            </label>
            <div class="layui-input-block">
                <div class="layui-inline" style="width:120px">
                    @Html.DropDownListFor(x => x.ApiUrlPrefix, ViewBag.MqRequestUrl as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "ApiUrlPrefix" }, { "lay-verify", "required" } })
                </div>
                <div class="layui-inline" style="width:240px">
                    @Html.TextBoxFor(x => x.ApiUrlSuffix, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入接口地址" } })
                </div>
                @Html.HiddenFor(x => x.ApiUrl)
                <span id="strapi" style="display:block; width:460px">@(Model.ApiUrl)</span>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                MQ路由:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.RoutingKey, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入路由地址" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>交换机:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.Exchange, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入交换机地址" } })
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>队列名称:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.QueueName, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入队列名称" } })
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>消费方式:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.MqMessageType, ViewBag.MQConsumerType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "MqMessageType" } })
            </div>
        </div>


        <div class="layui-form-item" id="div_TimeInterval">
            <label class="layui-form-label">
                <span class="we-red">*</span>时间间隔:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.TimeInterval, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "Pull获取消息时间间隔" } })
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>异常重试次数:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.ExceptionNumber, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "异常重试次数" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>失败消息存储:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.IsSaveFailMessage, ViewBag.MQFailMsgType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "IsSaveFailMessage" } })
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>任务状态:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.Status, ViewBag.StatusType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "Status" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
            </label>
            <div class="layui-input-block">
                <button class="layui-btn" lay-filter="Save" lay-submit="">保存</button>
            </div>
        </div>
    </form>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/MQBusiness/Index.cshtml
@{
    ViewBag.Title = "消息队列管理";
    ViewBag.Module = "消息队列任务列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userActions = ViewBag.UserActions as IEnumerable<TianYu.Core.Common.BaseViewModel.UserPrivilegeViewModel>;
}
<script>
    layui.use(['laydate', 'table', 'jquery', 'form'], function () {
            var laydate = layui.laydate
                , table = layui.table
                , $ = layui.jquery
                , form = layui.form;

            //初始化日期控件
            laydate.render({
                elem: '#CreateBeginTime'
            });
            //初始化日期控件
            laydate.render({
                elem: '#CreateEndTime'
            });

            //初始化表格数据
            table.render({
                elem: '#listTable'
                , toolbar: '#listToolbar'
                , limit:10
                , method: 'POST'
                , where: { }
                , url: '@Url.Action("FindList")' //数据接口
                , page: true //开启分页
                , request: {
                    pageName: 'pageIndex' //页码的参数名称，默认：page
                    , limitName: 'pageSize' //每页数据量的参数名，默认：limit
                }
                , parseData: function (res) { //res 即为原始返回的数据
                    var data = {
                        code: 0, //解析接口状态
                        msg: '', //解析提示文本
                        count: 0, //解析数据长度
                        data: [], //解析数据列表
                    };
                    if (res.Status == 200) {
                        res = res.Data;
                        if (res.Status == 1) {
                            data.count = res.Total;
                            data.data = res.BusinessData;
                        }
                        else {
                            data.code = 1;
                            data.msg = '业务错误：' + res.ErrorMessage + '，' + res.Status;
                        }
                    }
                    else {
                        data.code = 1;
                        data.msg = '请求错误：' + res.ErrorMessage + '，' + res.Status;
                    }

                    return data;
                }
                , cols: [[ //表头
                    { type: 'numbers', title: '#' }
                    , { type: 'checkbox' }
                    , { field: 'Id', title: 'Id', width: 100, align: 'center' }
                    , { field: 'BusinessName', title: '任务名称', width: 280, sort: true, align: 'center' }
                    , { field: 'ApiUrl', title: '请求地址', align: 'center' }
                    , { field: 'RoutingKey', title: '路由地址', width: 180, align: 'center' }
                    , { field: 'Exchange', title: '交换机', width: 180, align: 'center' }
                    , { field: 'QueueName', title: '队列名称', width: 250, align: 'center' }
                    , { field: 'StatusStr', title: '任务状态', width: 100, align: 'center' }
                    , { fixed: 'right', title: '操作', toolbar: '#rowToolbar', width: 220, align: 'center' }
                ]]
            });

            //按条件搜索数据
            form.on('submit(formSearch)', function (data) {
                reloadTable(data.field);
                return false;
            });
            /**
             * 重新加载表格
             * @@param data 条件
             */
          var reloadTable = function (data) {
              if (!data) { data = []; }
              table.reload('listTable', {
                  where: data
                  , page: {
                      curr: 1 //重新从第 1 页开始
                  }
              });
          };
          //监听事件
          table.on('toolbar(listTable)', function (obj) {
              var checkStatus = table.checkStatus(obj.config.id);
              switch (obj.event) {
                  case 'adds':
                      WeAdminShow("新增", "@Url.Action("Adds", "MQBusiness")",800,680);
                      break;
              };
          });

            //监听行工具事件
            table.on('tool(listTable)', function (obj) {
                var data = obj.data;
                if (obj.event == 'edit') {
                    WeAdminShow("编辑", "@Url.Action("Edits")?Id=" + data.Id, 800, 680);
                }
                if (obj.event == 'Detail') {
                    WeAdminShow("查看详情", "@Url.Action("Detail")?Id=" + data.Id, 800, 680);
                }
            });
        });
</script>
<div class="weadmin-body ">
    <div class="layui-row">
        <form class="layui-form layui-col-md12 we-search">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <div class="layui-inline">
                        <label class="layui-form-label">创建时间</label>
                        <div class="layui-input-block">
                            <div class="layui-inline">
                                <input name="CreateBeginTime" id="CreateBeginTime" placeholder="开始时间" class="layui-input search-date-input" autocomplete="off">
                            </div>
                            -
                            <div class="layui-inline">
                                <input name="CreateEndTime" id="CreateEndTime" placeholder="结束时间" class="layui-input search-date-input" autocomplete="off">
                            </div>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">关键字</label>
                        <div class="layui-input-block">
                            <input type="text" name="Keywords" placeholder="任务名称" class="layui-input">
                        </div>
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn" lay-submit="" lay-filter="formSearch"><i class="layui-icon">&#xe615;</i></button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/html" id="listToolbar">
        <div class="layui-btn-container">
            @*@if (userActions.Any(a => a.PowerName == "新增"))
                {
                    <button class="layui-btn layui-btn-sm layui-btn-danger" lay-event="adds">添加队列</button>
                }*@
            <button class="layui-btn layui-btn-sm layui-btn-danger" lay-event="adds">添加队列</button>
        </div>
    </script>
    <script type="text/html" id="rowToolbar">
        <a class="layui-btn layui-btn-xs" lay-event="Detail">查看</a>
        <a class="layui-btn layui-btn-danger layui-icon layui-btn-xs" lay-event="edit">编辑</a>
    </script>
    <table id="listTable" lay-filter="listTable"></table>
</div>