TianYu.Admin/TianYu.Admin.WebMvc/Controllers/SystemRoleController.cs
using TianYu.Core.Common;
using TianYu.Admin.Service.IService; 
using System.Web.Mvc;
using TianYu.Core.Common.FilterAttribute.Api;
using TianYu.Admin.Domain.ViewModel.Request; 

namespace TianYu.Admin.WebMvc.Controllers
{
    [ValidateLogin]
    public class SystemRoleController : BaseController
    {
        public ISystemRoleService _systemRoleService { get; set; } 
        public ISystemRoleRulesService _systemRoleRulesService { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Add()
        {
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Edit(QueryDetailSystemRoleRequestModel requestModel)
        {
            var systemRole = _systemRoleService.QueryDetail(requestModel);
            return View(systemRole.BusinessData);

        }
        /// <summary>
        /// 权限设置
        /// </summary>
        /// <param name="roleId">角色Id</param>
        /// <returns></returns>
        public ActionResult PowerSettings(int roleId)
        {
            ViewBag.RoleId = roleId;

            //获取所有菜单以及角色权限
            var menuList = _systemRoleService.FindMenuButtonRole(roleId); 

            return View(menuList);
        } 

        /// <summary>
        /// 添加角色
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Insert(AddSystemRoleRequestModel requestModel)
        {
            var res = _systemRoleService.Insert(requestModel);
            return Content(res.ToJsonString());
        }
        /// <summary>
        /// 角色查询
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Query(QuerySystemRoleRequestModel requestModel)
        {
            var res = _systemRoleService.Query(requestModel);
            return Content(res.ToJsonString());
        }
        /// <summary>
        /// 更新角色
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Update(UpdateSystemRoleRequestModel requestModel)
        {
            var res = _systemRoleService.Update(requestModel);
            return Content(res.ToJsonString());
        }
        /// <summary>
        /// 删除角色
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult Remove(RemoveSystemRoleRequestModel requestModel)
        {
            var res = _systemRoleService.Remove(requestModel);
            return Content(res.ToJsonString());
        }
        /// <summary>
        /// 设置角色权限
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public ActionResult SaveRolePowers(SetSystemRoleRulesRequestModel requestModel)
        {
            var ret = _systemRoleRulesService.SetSystemRoleRules(requestModel);
            return Content(ret.ToJsonString());
        } 
    }
}

TianYu.Admin/TianYu.Admin.WebMvc/Views/SystemRole/Add.cshtml
@model TianYu.Admin.Domain.ViewModel.Response.QueryDetailSystemRoleResponseModel

@{
    Layout = "~/Views/Shared/_Info.cshtml";
}

@section scripts{
    <script>

        layui.use(['jquery', 'form'], function () {
            var form = layui.form,
                $ = layui.jquery;
            //提交表单数据
            form.on('submit(Save)', function (data) {
                //禁用提交按钮
                toggleSubmitStatus(data.elem);

                var param = data.field;

                param.Enabled = true;
                //param.Status = $('#StatusBool').prop('checked') ? 1 : 0; 
                $.ajax({
                    type: 'post',
                     url: '@Url.Action("Insert")',
                    data: param,
                    dataType: 'json',
                    success: function (res) {  
                        if (res.Status == 200) {
                            res = res.Data;
                            if (res.Status == 1) {
                                //刷新列表
                                $(".layui-btn[lay-filter='formSearch']", window.parent.document).click();
                                layer.msg('保存成功', { time: 500 }, function () {
                                    //关闭当前弹出层
                                    var index = parent.layer.getFrameIndex(window.name);
                                    parent.layer.close(index);
                                });
                            }
                            else {
                                //启用提交按钮
                                toggleSubmitStatus(data.elem, true);
                                layer.msg(res.ErrorMessage);
                            }
                        }
                        else {
                            //启用提交按钮
                            toggleSubmitStatus(data.elem, true);
                            layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                        }
                    }
                });
                return false;
            });
        });
    </script>
}

<div class="weadmin-body">
    <form class="layui-form">
        @*隐藏字段*@
        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>角色名称
            </label>
            <div class="layui-input-block">
                <input type="text" name="RoleName" lay-verify="required" class="layui-input" placeholder="角色名称" />
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                角色编码
            </label>
            <div class="layui-input-block">
                <input type="text" name="RoleCode" class="layui-input" placeholder="角色编码" />
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                描述
            </label>
            <div class="layui-input-block">
                <textarea name="RoleDesc" cols="3" rows="3" placeholder="描述" class="layui-textarea"></textarea>
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">
            </label>
            <div class="layui-input-block">
                <button class="layui-btn" lay-filter="Save" lay-submit="">保存</button>
            </div>
        </div>

    </form>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/SystemRole/Edit.cshtml
@model TianYu.Admin.Domain.ViewModel.Response.QueryDetailSystemRoleResponseModel

@{
    Layout = "~/Views/Shared/_Info.cshtml";
}

@section scripts{
    <script>

        layui.use(['jquery', 'form'], function () {
            var form = layui.form,
                $ = layui.jquery;
            //提交表单数据
            form.on('submit(Save)', function (data) {
                //禁用提交按钮
                toggleSubmitStatus(data.elem);

                var param = data.field;

                param.Status = 1;
                //param.Status = $('#StatusBool').prop('checked') ? 1 : 0; 
                $.ajax({
                    type: 'post',
                     url: '@Url.Action("Update")',
                    data: param,
                    dataType: 'json',
                    success: function (res) { 
                        if (res.Status == 200) {
                            res = res.Data;
                            if (res.Status == 1) {
                                //刷新列表
                                $(".layui-btn[lay-filter='formSearch']", window.parent.document).click();
                                layer.msg('保存成功', { time: 500 }, function () {
                                    //关闭当前弹出层
                                    var index = parent.layer.getFrameIndex(window.name);
                                    parent.layer.close(index);
                                });
                            }
                            else {
                                //启用提交按钮
                                toggleSubmitStatus(data.elem, true);
                                layer.msg(res.ErrorMessage);
                            }
                        }
                        else {
                            //启用提交按钮
                            toggleSubmitStatus(data.elem, true);
                            layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                        }
                    }
                });
                return false;
            });
        });
    </script>
}

<div class="weadmin-body">
    <form class="layui-form">
        @*隐藏字段*@
        @Html.HiddenFor(x => x.Id)
        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>角色名称
            </label>
            <div class="layui-input-block">
                @Html.TextBoxFor(x => x.RoleName, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "角色名称" } })
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                角色编码
            </label>
            <div class="layui-input-block">
                @Html.TextBoxFor(x => x.RoleCode, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "角色编码" } })
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">
                描述
            </label>
            <div class="layui-input-block">
                <textarea name="RoleDesc" cols="3" rows="3" placeholder="描述" class="layui-textarea">@Model.RoleDesc</textarea> 
            </div>
        </div>


        @*<div class="layui-form-item">
                <label class="layui-form-label">
                    账号启用状态
                </label>
                <div class="layui-input-block">
                    @Html.CheckBoxFor(x => x.StatusBool, new Dictionary<string, object> { { "lay-skin", "switch" } })
                </div>
            </div>*@

        <div class="layui-form-item">
            <label class="layui-form-label">
            </label>
            <div class="layui-input-block">
                <button class="layui-btn" lay-filter="Save" lay-submit="">保存</button>
            </div>
        </div>

    </form>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/SystemRole/Index.cshtml
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="weadmin-body ">
    <div class="layui-row">
        <form class="layui-form layui-col-md12 we-search">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">查询内容</label>
                    <div class="layui-input-block">
                        <div class="layui-inline">
                            <input name="KeyWord" id="KeyWord" placeholder="角色名称" class="layui-input search-input">
                        </div>
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn" lay-submit="" lay-filter="formSearch"><i class="layui-icon">&#xe615;</i></button>
                </div>
            </div>
        </form>
    </div>
    <!-- 这里的 显示/隐藏 -->
    <script type="text/html" id="switchTpl">
        <input type="checkbox" name="Status" value="{{d.Id}}" lay-skin="switch" disabled lay-text="启用|禁用" lay-filter="switch1" {{ d.Enabled == 1 ? 'checked' : '' }}>
    </script>
    <table id="listTable" lay-filter="listTable"></table>
</div>

@section scripts{

    <script>
    layui.use(['laydate', 'table', 'jquery', 'form'], function () {
        var laydate = layui.laydate
            , table = layui.table
            , $ = layui.jquery
            , form = layui.form;

        //初始化日期控件
        laydate.render({
            elem: '#CreateBeginTime'
        });
        //初始化日期控件
        laydate.render({
            elem: '#CreateEndTime'
        });

        //初始化表格数据
        table.render({
            elem: '#listTable'
            , toolbar: '#listToolbar'
            , limit: 10
            , method: 'POST'
            , where: {}
            , url: '@Url.Action("Query")' //数据接口
            , page: true //开启分页
            , request: {
                pageName: 'pageIndex' //页码的参数名称，默认：page
                , limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            , parseData: function (res) { //res 即为原始返回的数据
                var data = {
                    code: 0, //解析接口状态
                    msg: '', //解析提示文本
                    count: 0, //解析数据长度
                    data: [], //解析数据列表
                };
                if (res.Status == 200) {
                    res = res.Data;
                    if (res.Status == 1) {
                        data.count = res.Total;
                        data.data = res.BusinessData;
                    }
                    else {
                        data.code = 1;
                        data.msg = '业务错误：' + res.ErrorMessage + '，' + res.Status;
                    }
                }
                else {
                    data.code = 1;
                    data.msg = '请求错误：' + res.ErrorMessage + '，' + res.Status;
                }

                return data;
            }
            , cols: [[ //表头
                { type: 'numbers', title: '#' }
                , { type: 'checkbox' }
                , { field: 'RoleName', title: '角色名称', width: 200, sort: true, align: 'center' }
                , { field: 'RoleCode', title: '角色编码', width: 200, sort: true, align: 'center' }
                , { field: 'Enabled', title: '启用|禁用', width: 100, templet: '#switchTpl', unresize: true }
                , { field: 'CreateTime', title: '创建时间', width: 160, align: 'center' }
                , { field: 'ModifyTime', title: '修改时间', width: 160, align: 'center' }
                , { fixed: 'right', title: '操作', toolbar: '#rowToolbar', minWidth: 320, align: 'center' }
            ]]
        });

        //按条件搜索数据
        form.on('submit(formSearch)', function (data) {
            reloadTable(data.field);
            return false;
        });
        /**
         * 重新加载表格
         * @@param data 条件
         */
        var reloadTable = function (data) {
            if (!data) { data = []; }
            table.reload('listTable', {
                where: data
                , page: {
                    curr: 1 //重新从第 1 页开始
                }
            });
        };
        //监听事件
        table.on('toolbar(listTable)', function (obj) {
            switch (obj.event) {
                case 'Insert':
                    ShowWindow("新增", "@Url.Action("Add", "SystemRole")", 450, 380);
                    break;

            };
        });

        //监听行工具事件
        table.on('tool(listTable)', function (obj) {
            var data = obj.data;
            switch (obj.event) {
                case 'Remove':
                    layer.confirm('确定要删除当前选中的数据?', { icon: 3, title: '提示' }, function (index) {
                        batchDelete(data.Id);
                        layer.close(index);
                    });
                    break;
                case 'Update':
                    ShowWindow("编辑", "@Url.Action("Edit")?Id=" + data.Id, 450, 380);
                    break;
                case 'SetPower':
                    ShowWindow("权限设置", "@Url.Action("PowerSettings")?RoleId=" + data.Id,900);
                    break;
            }
        });

        /*
         * 批量删除数据
         * @@param ids 数据Id集合
         */
        var batchDelete = function (ids) {
            var index = layer.load(2, { time: 60 * 1000 });
            $.ajax({
                type: 'post',
                dataType: 'json',
                url: '@Url.Action("Remove")',
                data: { Id: ids },
                success: function (res) {
                    layer.close(index);
                    if (res.Status == 200) {
                        res = res.Data;
                        if (res.Status == 1) {
                            layer.msg("删除成功");
                            reloadTable();//重新加载表格数据
                        }
                        else {
                            layer.msg(res.ErrorMessage);
                        }
                    }
                    else {
                        layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                    }
                },
                error: function (res) {
                    layer.close(index);
                    layer.msg("请求出错");
                    console.log(res);
                }

            });
        };
    });

    </script>
}

TianYu.Admin/TianYu.Admin.WebMvc/Views/SystemRole/PowerSettings.cshtml
@using TianYu.Admin.Domain.ViewModel
@model List<SystemMenuButtonRoleViewModel>
@{ 
    Layout = "~/Views/Shared/_Info.cshtml";
}

@section styles{
    <link href="/Content/layui/lay/extend/treetable.css" rel="stylesheet" />
}
<div class="weadmin-body">
    <form class="layui-form">
        <div class="layui-tab" lay-filter="details">
            <div class="layui-tab-content">
                <div class="layui-tab-item editUserInfo layui-show orderCenter">
                    <table cellspacing="0" cellpadding="0" border="0" class="layui-table" lay-filter="Pertable">
                        <thead>
                            <tr>
                                <th>
                                    菜单
                                </th>
                                <th>
                                    操作权限
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var menu in Model)  
                            {
                                <tr class="tableModule">
                                    <!--菜单名-->
                                    <td style="width: 250px">
                                        <div class="layui-table-cell">
                                            @for (var i = 1; i < menu.Level; i++)
                                            {
                                                <span class="treeTable-empty"></span>
                                            }
                                            <span class="treeTable-icon open">
                                                @if (menu.Level != 3)
                                                {
                                                    <i class="layui-icon layui-icon-triangle-d"></i>
                                                }
                                                else
                                                {
                                                    <span class="treeTable-empty"></span>
                                                }
                                                &nbsp;@menu.MenuName
                                            </span>
                                        </div>
                                    </td>
                                    <td class="selfStyle">
                                        <!--功能名称-->
                                        <ul style="float: left;display: block;margin-left:20px;">
                                            @if (menu.ButtonList != null)
                                            {
                                                foreach (var action in menu.ButtonList)
                                                {
                                                    <li style="float: left;">
                                                        <input type="checkbox" name="SelectedButton" lay-filter="cbo" lay-skin="primary" data-code="@(menu.MenuCode + action.Id)" data-menuid="@menu.Id" data-actionid="@action.Id" title="@action.ButtonName" @(action.IsChecked ? "checked" : "") />
                                                    </li>
                                                }
                                            }
                                            else
                                            {
                                                <li style="float: left;display:none">
                                                    <input type="checkbox" name="SelectedButton" lay-skin="primary" data-code="@menu.MenuCode" data-menuid="@menu.Id" data-actionid="0" @(menu.IsChecked ? "checked" : "") />
                                                </li>
                                            }
                                        </ul>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <div class="layui-form-item ">
                    <div style="margin-top:20px;" align="center">
                        <input type="hidden" name="RoleId" id="RoleId" value="@ViewBag.RoleId" />
                        <button class="layui-btn" lay-filter="Save" lay-submit="">保存</button>
                    </div>
                </div>

                @*<div class="layui-btn layui-btn-fluid  layui-btn-primary" style="background-color:rgba(249, 250, 252, 1); height: 50px; line-height: 50px;">
                        <span class="layui-unselect layui-form-checkbox" lay-skin="primary"><i class="layui-icon layui-icon-ok"></i></span> 全部选择
                        </span>
                    </div>*@
            </div>
        </div>
    </form>
</div>
@section scripts{
    <script>
        layui.use(['jquery', 'form'], function () {
            var form = layui.form
                , $ = layui.jquery;

            function checkedBox(code, isChecked) {

                var codeLevel = parseInt(code / 100);

                if (codeLevel < 1000) return;

                if (isChecked) {
                    $("input[type=checkbox][data-code=" + codeLevel + "]").prop("checked", "true");
                } else {
                    var list = $("input[type=checkbox][data-code^=" + codeLevel + "]:checked");
                    if (list.length == 1) {
                        $("input[type=checkbox][data-code=" + codeLevel + "]:checked").removeAttr("checked");
                    }
                }
                checkedBox(codeLevel, isChecked);
            }

            form.on("checkbox(cbo)", function () {
                var code = parseInt($(this).data('code'));
                checkedBox(code, $(this).is(":checked"));
                form.render(); 
            });
             
            form.on('submit(Save)', function (data) {
                //禁用提交按钮
                toggleSubmitStatus(data.elem);

                var roleId = $("#RoleId").val();
                var allCheckBoxs = $("input[type=checkbox]:checked");
                var checkArry = Array();
                for (var i = 0; i < allCheckBoxs.length; i++) {
                    var $this = $(allCheckBoxs[i]);
                    var actionid = $this.data('actionid');
                    var menuId = $this.data('menuid');
                    if (id != "" && id != undefined && id != null) {
                        var obj = {};
                        obj.MenuId = menuId
                        obj.ButtonId = actionid;
                        checkArry[i] = obj;
                    }
                }

                $.ajax({
                    url: "SaveRolePowers",
                    type: "post",
                    async: false,
                    dataType: 'json',
                    data: { RoleId: roleId, list: checkArry },
                    success: function (res) {
                        if (res.Status == 200) {
                            res = res.Data;
                            if (res.Status == 1) {
                                layer.msg('保存成功', { time: 500 }, function () {
                                    //关闭当前弹出层
                                    var index = parent.layer.getFrameIndex(window.name);
                                    parent.layer.close(index);
                                });
                            }
                            else {
                                //启用提交按钮
                                toggleSubmitStatus(data.elem, true);
                                layer.msg(res.ErrorMessage);
                            }
                        }
                        else {
                            //启用提交按钮
                            toggleSubmitStatus(data.elem, true);
                            layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                        }
                    }
                });
            })
        });

    </script>
}