TianYu.Admin/TianYu.Admin.WebMvc/Controllers/ScheduleTaskController.cs
using TianYu.Core.Common; 
using TianYu.Admin.Domain.ViewModel;
using TianYu.Admin.Infrastructure.Enum;
using TianYu.Admin.Service.IService; 
using System.Web.Mvc;
using TianYu.Core.Common.FilterAttribute.Api;

namespace TianYu.Admin.WebMvc.Controllers
{
    [ValidateLogin]
    public class ScheduleTaskController : BaseController
    {
        #region 变量
        /// <summary>
        /// 业务逻辑服务接口
        /// </summary>
        private IScheduleTaskConfigService _scheduleTaskConfigService;
        #endregion

        #region 构造
        /// <summary>
        /// 构造
        /// </summary>
        /// <param name="scheduleTaskConfigService"></param>
        public ScheduleTaskController(IScheduleTaskConfigService scheduleTaskConfigService)
        {
            this._scheduleTaskConfigService = scheduleTaskConfigService;
        }
        #endregion

        #region 视图
        /// <summary>
        /// index
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            GetListItemByEnum();
            return View();
        }

        /// <summary>
        /// 新增
        /// </summary>
        /// <returns></returns> 
        public ActionResult Adds()
        {
            ScheduleTaskResponse model = new ScheduleTaskResponse();
            GetListItemByEnum();
            return View(model);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns></returns> 
        public ActionResult Edits(ScheduleTaskInfoRequest request)
        {
            GetListItemByEnum();
            var model = _scheduleTaskConfigService.FindInfoById(request.Id);
            if (model == null)
            {
                return GoErrorPage("定时任务信息不存在或已被删除");
            }
            return View(model);
        }

        /// <summary>
        /// 详情
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns> 
        public ActionResult Detail(ScheduleTaskInfoRequest request)
        {
            GetListItemByEnum();
            if (request?.Id <= 0)
            {
                return GoErrorPage("参数传递错误");
            }

            var viewModel = _scheduleTaskConfigService.FindInfoById(request.Id);
            if (viewModel == null)
            {
                return GoErrorPage("定时任务信息不存在或已被删除");
            }
            return View(viewModel);
        }

        private void GetListItemByEnum()
        {
            ViewBag.TaskStatusType = base.GetSelectListItemByEnum<CommonStatusType>(false);
            ViewBag.TaskExecuteType = base.GetSelectListItemByEnum<TaskExecuteType>(false);
        }
        #endregion

        #region 动作
        /// <summary>
        /// 任务列表
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FindList(ScheduleTaskRequest request)
        {
            var res = _scheduleTaskConfigService.FindList(request);
            return Content(res.ToJsonString());
        }


        /// <summary>
        /// 新增或更新
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult AddOrUpsert(ScheduleTaskAddOrUpsertRequest model)
        {
            var res = _scheduleTaskConfigService.AddOrUpsert(model);
            return Content(res.ToJsonString());
        }
        #endregion

    }
}

TianYu.Admin/TianYu.Admin.WebMvc/Views/ScheduleTask/Adds.cshtml
@model TianYu.Admin.Domain.ViewModel.ScheduleTaskResponse

@{
    ViewBag.Module = "定时任务列表";
    ViewBag.Title = "添加任务";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script>
        layui.use(['jquery', 'form'], function () {
            var form = layui.form,
                $ = layui.jquery;
            //提交表单数据
            form.on('submit(Save)', function (data) {
                //禁用提交按钮
                toggleSubmitStatus(data.elem);
                var param = data.field;
                var index = layer.load(1, { time: 60 * 1000 });
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("AddOrUpsert")',
                    data: param,
                    dataType: 'json',
                    success: function (res) {
                        layer.close(index);
                        if (res.Status == 200) {
                            res = res.Data;
                            if (res.Status == 1) {
                                //刷新列表
                                $(".layui-btn[lay-filter='formSearch']", window.parent.document).click();
                                layer.msg('保存成功', function () {
                                    //启用提交按钮
                                    toggleSubmitStatus(data.elem, true);
                                    //关闭当前弹出层
                                    var index = parent.layer.getFrameIndex(window.name);
                                    parent.layer.close(index);
                                });
                            }
                            else {
                                //启用提交按钮
                                toggleSubmitStatus(data.elem, true);
                                layer.msg(res.ErrorMessage);
                            }
                        }
                        else {
                            //启用提交按钮
                            toggleSubmitStatus(data.elem, true);
                            layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                        }
                    }
                });
            });
        });
    </script>
}

<div class="weadmin-body">
    <form class="layui-form">
        <div class="layui-form-item">
            <label class="layui-form-label">
                <input type="hidden" name="Id" value="@Model.Id" />
                <span class="we-red">*</span>任务名称：
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.TaskName, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入任务名称" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>接口地址:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.ApiUrl, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入接口地址" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                请求参数:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.Parameters, new Dictionary<string, object> { { "class", "layui-input" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>请求谓词:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.Method, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "POST" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>执行方式:
            </label>
            <div class="layui-input-block" style="width:50%">
                
                @Html.DropDownListFor(x => x.ExecuteType, ViewBag.TaskExecuteType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "selType" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>异常重试次数:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.ExceptionNumber, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "异常重试次数" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>间隔时间（秒）:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.DiffSeconds, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "间隔时间（秒）" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>任务状态:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.Status, ViewBag.TaskStatusType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "selType" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
            </label>
            <div class="layui-input-block">
                <button class="layui-btn" lay-filter="Save" lay-submit="">保存</button>
            </div>
        </div>

    </form>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/ScheduleTask/Detail.cshtml
@{
    ViewBag.Module = "定时任务列表";
    ViewBag.Title = "定时任务详情";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="weadmin-body">
    <div class="layui-card">
        <div class="layui-card-header">定时任务明细</div>
        <div class="layui-card-body">
            <table class="layui-table details-info-table">
                <colgroup>
                    <col width="130">
                    <col>
                </colgroup>
                <tbody>
                    <tr>
                        <th class="layui-bg-gray">任务名称</th>
                        <td>@Model.TaskName</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">请求参数</th>
                        <td>@Model.Parameters</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">请求方式</th>
                        <td>@Model.Method</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">执行方式</th>
                        <td>@(Model.ExecuteType == 0 ? "循环执行" : "其他")</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">接口地址</th>
                        <td>@Model.ApiUrl</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">重试次数</th>
                        <td>@Model.ExceptionNumber</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">间隔时间</th>
                        <td>@Model.DiffSeconds</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">运行状态</th>
                        <td>@Model.RunStatusName</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">任务状态</th>
                        <td>@Model.StatusName</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">最后执行时间</th>
                        <td>@Model.LastRunTime</td>
                    </tr>
                    <tr>
                        <th class="layui-bg-gray">创建时间</th>
                        <td>@Model.CreateTime</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/ScheduleTask/Edits.cshtml
@model TianYu.Admin.Domain.ViewModel.ScheduleTaskResponse
@{
    ViewBag.Module = "定时任务列表";
    ViewBag.Title = "编辑任务";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script>
        layui.use(['jquery', 'form'], function () {
            var form = layui.form,
                $ = layui.jquery;
            //提交表单数据
            form.on('submit(Save)', function (data) {
                //禁用提交按钮
                toggleSubmitStatus(data.elem);
                var param = data.field;
                var index = layer.load(1, { time: 60 * 1000 });
                $.ajax({
                    type: 'post',
                    url: '@Url.Action("AddOrUpsert")',
                    data: param,
                    dataType: 'json',
                    success: function (res) {
                        layer.close(index);
                        if (res.Status == 200) {
                            res = res.Data;
                            if (res.Status == 1) {
                                //刷新列表
                                $(".layui-btn[lay-filter='formSearch']", window.parent.document).click();
                                layer.msg('保存成功', function () {
                                    //启用提交按钮
                                    toggleSubmitStatus(data.elem, true);
                                    //关闭当前弹出层
                                    var index = parent.layer.getFrameIndex(window.name);
                                    parent.layer.close(index);
                                });
                            }
                            else {
                                //启用提交按钮
                                toggleSubmitStatus(data.elem, true);
                                layer.msg(res.ErrorMessage);
                            }
                        }
                        else {
                            //启用提交按钮
                            toggleSubmitStatus(data.elem, true);
                            layer.msg('请求错误：' + res.ErrorMessage + '，' + res.Status);
                        }
                    }
                });
            });
        });
    </script>
}

<div class="weadmin-body">
    <form class="layui-form">
        <div class="layui-form-item">
            <label class="layui-form-label">
                <input type="hidden" name="Id" value="@Model.Id" />
                <span class="we-red">*</span>任务名称：
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.TaskName, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入任务名称" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>接口地址:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.ApiUrl, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "请输入接口地址" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                请求参数:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.Parameters, new Dictionary<string, object> { { "class", "layui-input" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>请求谓词:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.Method, new Dictionary<string, object> { { "lay-verify", "required" }, { "class", "layui-input" }, { "placeholder", "POST" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>执行方式:
            </label>
            <div class="layui-input-block" style="width:50%">

                @Html.DropDownListFor(x => x.ExecuteType, ViewBag.TaskExecuteType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "selType" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>异常重试次数:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.ExceptionNumber, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "异常重试次数" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>间隔时间（秒）:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.TextBoxFor(x => x.DiffSeconds, new Dictionary<string, object> { { "lay-verify", "required|number" }, { "class", "layui-input" }, { "placeholder", "间隔时间（秒）" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
                <span class="we-red">*</span>任务状态:
            </label>
            <div class="layui-input-block" style="width:50%">
                @Html.DropDownListFor(x => x.Status, ViewBag.TaskStatusType as IEnumerable<SelectListItem>, new Dictionary<string, object> { { "lay-filter", "selType" } })
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">
            </label>
            <div class="layui-input-block">
                <button class="layui-btn" lay-filter="Save" lay-submit="">保存</button>
            </div>
        </div>

    </form>
</div>

TianYu.Admin/TianYu.Admin.WebMvc/Views/ScheduleTask/Index.cshtml
@{
    ViewBag.Title = "定时任务管理";
    ViewBag.Module = "定时任务列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userActions = ViewBag.UserActions as IEnumerable<TianYu.Core.Common.BaseViewModel.UserPrivilegeViewModel>;
}

<script>
    layui.use(['laydate', 'table', 'jquery', 'form'], function () {
            var laydate = layui.laydate
                , table = layui.table
                , $ = layui.jquery
                , form = layui.form;

            //初始化日期控件
            laydate.render({
                elem: '#CreateBeginTime'
            });
            //初始化日期控件
            laydate.render({
                elem: '#CreateEndTime'
            });

            //初始化表格数据
            table.render({
                elem: '#listTable'
                , toolbar: '#listToolbar'
                , limit:10
                , method: 'POST'
                , where: { }
                , url: '@Url.Action("FindList")' //数据接口
                , page: true //开启分页
                , request: {
                    pageName: 'pageIndex' //页码的参数名称，默认：page
                    , limitName: 'pageSize' //每页数据量的参数名，默认：limit
                }
                , parseData: function (res) { //res 即为原始返回的数据
                    var data = {
                        code: 0, //解析接口状态
                        msg: '', //解析提示文本
                        count: 0, //解析数据长度
                        data: [], //解析数据列表
                    };
                    if (res.Status == 200) {
                        res = res.Data;
                        if (res.Status == 1) {
                            data.count = res.Total;
                            data.data = res.BusinessData;
                        }
                        else {
                            data.code = 1;
                            data.msg = '业务错误：' + res.ErrorMessage + '，' + res.Status;
                        }
                    }
                    else {
                        data.code = 1;
                        data.msg = '请求错误：' + res.ErrorMessage + '，' + res.Status;
                    }

                    return data;
                }
                , cols: [[ //表头
                    { type: 'numbers', title: '#' }
                    , { type: 'checkbox' }
                    , { field: 'Id', title: 'Id', width: 100, align: 'center' }
                    , { field: 'TaskName', title: '任务名称', width: 280, sort: true, align: 'center' }
                    , { field: 'ApiUrl', title: '请求地址', align: 'center' }
                    , { field: 'ExceptionNumber', title: '异常重试次数', width: 180, align: 'center' }
                    , { field: 'StatusName', title: '状态', width: 180, align: 'center' }
                    , { field: 'CreateTime', title: '创建时间', width: 250, align: 'center' }
                    , { fixed: 'right', title: '操作', toolbar: '#rowToolbar', width: 320, align: 'center' }
                ]]
            });

            //按条件搜索数据
            form.on('submit(formSearch)', function (data) {
                reloadTable(data.field);
                return false;
            });
            /**
             * 重新加载表格
             * @@param data 条件
             */
          var reloadTable = function (data) {
              if (!data) { data = []; }
              table.reload('listTable', {
                  where: data
                  , page: {
                      curr: 1 //重新从第 1 页开始
                  }
              });
          };
          //监听事件
          table.on('toolbar(listTable)', function (obj) {
              var checkStatus = table.checkStatus(obj.config.id);
              switch (obj.event) {
                  case 'adds':
                      WeAdminShow("新增", "@Url.Action("Adds", "ScheduleTask")",800,680);
                      break;
              };
          });

            //监听行工具事件
            table.on('tool(listTable)', function (obj) {
                var data = obj.data;
                if (obj.event == 'edit') {
                    WeAdminShow("编辑", "@Url.Action("Edits")?Id=" + data.Id, 800, 680);
                }
                if (obj.event == 'Detail') {
                    WeAdminShow("查看详情", "@Url.Action("Detail")?Id=" + data.Id, 800, 680);
                }
            });
        });
</script>

<div class="weadmin-body ">
    <div class="layui-row">
        <form class="layui-form layui-col-md12 we-search">
            <div class="layui-form-item">
                <div class="layui-inline">

                    <div class="layui-inline">
                        <label class="layui-form-label">创建时间</label>
                        <div class="layui-input-block">
                            <div class="layui-inline">
                                <input name="CreateBeginTime" id="CreateBeginTime" placeholder="开始时间" class="layui-input search-date-input" autocomplete="off">
                            </div>
                            -
                            <div class="layui-inline">
                                <input name="CreateEndTime" id="CreateEndTime" placeholder="结束时间" class="layui-input search-date-input" autocomplete="off">
                            </div>
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">关键字</label>
                        <div class="layui-input-block">
                            <input type="text" name="Keywords" placeholder="任务名称" class="layui-input">
                        </div>
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn" lay-submit="" lay-filter="formSearch"><i class="layui-icon">&#xe615;</i></button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/html" id="listToolbar">
        <div class="layui-btn-container">
            @*@if (userActions.Any(a => a.PowerName == "新增"))
            {
                <button class="layui-btn layui-btn-sm layui-btn-danger" lay-event="adds">添加任务</button>
            }*@
            <button class="layui-btn layui-btn-sm layui-btn-danger" lay-event="adds">添加任务</button>
        </div>
    </script>
    <script type="text/html" id="rowToolbar">
        <a class="layui-btn layui-btn-xs" lay-event="Detail">查看</a>
        <a class="layui-btn layui-btn-danger layui-icon layui-btn-xs" lay-event="edit">编辑</a>
    </script>
    <table id="listTable" lay-filter="listTable"></table>
</div>